# Generated by Django 5.2.8 on 2025-11-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50, unique=True, verbose_name='Control Number / 001')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN / 020')),
                ('title', models.CharField(max_length=255, verbose_name='Title / 245$a')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle / 245$b')),
                ('statement_of_responsibility', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statement of Responsibility / 245$c')),
                ('author', models.CharField(max_length=255, verbose_name='Main Author / 100$a')),
                ('added_authors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Added Authors / 700$a')),
                ('edition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Edition / 250')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher / 264$b')),
                ('publication_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place / 264$a')),
                ('publication_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Year / 264$c')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pagination / 300$a')),
                ('illustrations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Illustrations / 300$b')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimensions / 300$c')),
                ('series', models.CharField(blank=True, max_length=255, null=True, verbose_name='Series / 490$a')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='General Notes / 500')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary / 520')),
                ('subjects', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjects / 650$a')),
                ('classification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dewey / 082 or Local / 090')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language / 041$a')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
