# Generated by Django 5.2.8 on 2025-11-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
