# Generated by Django 5.2.8 on 2025-11-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_borrowedbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='app2.book')),
            ],
        ),
    ]
