# Generated by Django 5.2.8 on 2025-11-19 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_bookbarcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbarcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookbarcode',
            name='barcode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
