# Generated by Django 5.2.8 on 2025-11-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_bookbarcode_created_at_alter_bookbarcode_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_records', to='app2.bookbarcode'),
        ),
    ]
