# Generated by Django 5.2.8 on 2025-11-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='file_size',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='paper_size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
