# Generated by Django 5.2.8 on 2025-11-20 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app1.folder'),
        ),
    ]
